site_name: Openveo Manage
repo_url: https://github.com/veo-labs/openveo-manage
theme: readthedocs
site_dir: site/version
markdown_extensions:
  - fenced_code
  - tables
pages:
- 'INTRODUCTION': 'index.md'
- 'USERS':
  - 'Getting started': 'getting-started.md'
- 'PLUGINS DEVELOPERS':
  - 'API' : 'pluginsDevelopers/api.md'
- 'MANAGE DEVELOPERS':
  - 'Basics': 'developers/basics.md'
  - 'Installation': 'developers/installation.md'
  - 'Back end AngularJS': 'developers/back-end.md'
  - 'CSS / SASS / JS compilation': 'developers/compilation.md'
  - 'Unit tests': 'developers/unit-tests.md'
  - 'API': 'developers/api.md'
